apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cs179i-project
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "75"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "20"
    spec:
      containers:
        - image: bdenz001/cs179i-project:0.0.2.RELEASE
          ports:
            - containerPort: 5000
