apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cs179i-project
spec:
  template:
    spec:
      containers:
        - image: bdenz001/cs179i-project:0.0.1.RELEASE
          ports:
            - containerPort: 5000
